name: 🐞 Bug Report
description: Report a problem with the Discord Webhook Status plugin
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to help improve **Discord Webhook Status**!

        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of Discord Webhook Status are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Server Version
      description: What version of Minecraft or server software (e.g., Paper, Spigot) are you using?
      placeholder: e.g., Paper 1.20.4
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java is the server running?
      placeholder: e.g., Java 17
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Relevant Config Snippet (if applicable)
      description: Paste the relevant part of your config.yml if it's related to the issue.
      render: yaml

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe what went wrong. What did you expect to happen?
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Explain how to trigger the bug. A numbered list is helpful!
      placeholder: |
        1. Go to '...'
        2. Use this config setting '...'
        3. Run the command '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Server Console Logs or Error
      description: Paste any relevant errors from your server log here.
      render: text

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      description: Please confirm the following:
      options:
        - label: I am using the latest version of the plugin
          required: true
        - label: I have checked the existing issues to avoid duplicates
          required: true
        - label: I have reviewed my config for typos or misconfigurations
          required: true
